---
- name: Install and run Nginx
  yum: name=nginx state=latest

- name: Move default.conf
  command: mv /etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf.bak

- name: Move ssl.conf
  command: mv /etc/nginx/conf.d/ssl.conf /etc/nginx/conf.d/ssl.conf.bak

- name: Move virtual.conf
  command: mv /etc/nginx/conf.d/virtual.conf /etc/nginx/conf.d/virtual.conf.bak

- name: Configure Nginx
  template: src=nginx.conf dest=/etc/nginx/nginx.conf

- name: Create Magento root
  file: path={{magento_root}} state=directory

- name: Configure Nginx for Magento
  template: src=magento.conf dest=/etc/nginx/conf.d/magento.conf
