---
- name: Prepare repo REMI PHP 5.6
  command: yum install -y http://rpms.famillecollet.com/enterprise/remi-release-6.rpm

- name: Install PHP-FPM 5.6 from REMI repo
  yum: name={{ item }} state=installed enablerepo=remi-php56 
  with_items:
   - php.x86_64
   - php-bcmath.x86_64
   - php-cli.x86_64
   - php-common.x86_64
   - php-dba.x86_64
   - php-fpm.x86_64
   - php-gd.x86_64
   - php-mbstring.x86_64
   - php-mcrypt.x86_64
   - php-mysql.x86_64
   - php-pdo.x86_64
   - php-pear.noarch
   - php-pecl-zendopcache.x86_64
   - php-soap.x86_64
   - php-xml.x86_64
   - php-xmlrpc.x86_64
   - php-intl.x86_64
   - php-pecl-redis.x86_64

- name: Configure PHP-FPM [www] pool
  template: src=www.conf dest=/etc/php-fpm.d/www.conf owner=root group=root mode=0644

