---
- template: src=percona.repo dest=/etc/yum.repos.d/percona.repo owner=root group=root mode=0644

- template: src=my.cnf dest=/etc/my.cnf owner=root group=root mode=0644
  
- yum: enablerepo=percona pkg={{item}} state=installed
  with_items:
  - Percona-Server-client-55
  - Percona-Server-server-55
  - MySQL-python
  - libselinux-python
